### ISSUE TITLE
currency not showing

### ISSUE THREAD

**Issue by riadlynx** [Magento2Translations/language_ar_sa#3] opened 2016-11-21 20:11 UTC
Hi,
When i use this local currency symbole does not appear, can you please fix it? 
thanks

**Comment by HazemKhaled** [comment] 2016-11-21 21:01
More details @riadlynx, this repo only package translations from crowdin.com, so better to open this link, search you missing or wrong work and fix it.
https://crowdin.com/translate/magento-2/1374/enus-ar

within days you will find update there in this package

**Comment by MrGekko** [comment] 2016-11-22 07:27
I am not sure what the problem is. Is it the translation of the symbol in the csv or something in Magento blocking your curency symbol. When you disabled/removed this module does the currency symbole show up?

**Comment by riadlynx** [comment] 2016-11-22 07:36
yes when i use another language it works

**Comment by MrGekko** [comment] 2016-11-22 09:04
Could you try this when the package is activated? https://www.youtube.com/watch?v=NjBuRbNydX8

**Comment by riadlynx** [comment] 2016-11-22 18:58
unfortunately still not working

**Comment by MrGekko** [comment] 2017-01-09 08:16
Have you found a sollution to this problem? I am not sure what to do about it, so i am closing this issue.

**Closed by MrGekko** 2017-01-09 08:16 UTC
